resources:
  - name: myrepo
    type: GitRepo
    configuration:
      gitProvider: nagarjuntestpipelinegit   # replace with your integration
      path: amithkm/jfrog-pipelines-docker-sample    # replace with your repository name
      branches:
        include: master

  - name: dbp_image_1
    type: Image
    configuration:
      registry: nagarjunarttoken      # replace with your artifactory integration
      sourceRepository: docker   # required if registry is Artifactory
      imageName: swarnenduk-docker.jfrog.io/alpine/terragru # replace with your image path and name
      imageTag: latest
      autoPull: true

pipelines:
  - name: pipeline_dbp
    configuration:
      nodePool: default-dynamic-nodepool
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: swarnenduk-docker.jfrog.io/artifactory/alpine/terragru  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: myrepo
          integrations:
            - name: nagarjunarttoken    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker
          integrations:
            - name: nagarjunarttoken    # replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image_1
            


