resources:
  - name: myrepo
    type: GitRepo
    configuration:
      gitProvider: jfrogpipelines_pipelinesample   # replace with your integration
      path: amithkm/jfrog-pipelines-docker-sample    # replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: satheeshart      # replace with your artifactory integration
      sourceRepository: docker-local   # required if registry is Artifactory
      imageName: alpine/terragru  # replace with your image path and name
      imageTag: latest
      autoPull: true

pipelines:
  - name: pipeline_dbp
    configuration:
      nodePool: default-dynamic-nodepool
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: alpine/terragru  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: myrepo
          integrations:
            - name: satheeshart    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: satheeshart    # replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image
