resources:
  - name: myrepo
    type: GitRepo
    configuration:
      gitProvider: jfrogpipelines_pipelinesample   # replace with your integration
      path: amithkm/jfrog-pipelines-docker-sample    # replace with your repository name
      branches:
        include: master

  - name: dbp_image_1
    type: Image
    configuration:
      registry: satheeshart      # replace with your artifactory integration
      sourceRepository: amithkm-docker-virtual   # required if registry is Artifactory
      imageName: satheeshart-amithkm-docker-virtual.jfrog.io/alpine/terragru # replace with your image path and name
      imageTag: 0.12.26
      autoPull: true

pipelines:
  - name: pipeline_dbp
    configuration:
      nodePool: default-dynamic-nodepool
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: satheeshart-amithkm-docker-virtual.jfrog.io/alpine/terragru  # replace with your image path and name
          dockerImageTag: 0.12.26
          inputResources:
            - name: myrepo
          integrations:
            - name: satheeshart    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: amithkm-docker-virtual
          integrations:
            - name: satheeshart    # replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image_1
